### ISSUE TITLE
Update ERD

### ISSUE THREAD

**Issue by digawp** [exclusive-gix/cs2102-store#42]
- [x] Organisation is now in connected to multimedia instead of crew ( #38 )
- [x] Link review table with user table (#56) 
- [x] Review table now has created_at timestamp ( #56 )
- [x] Ignore table transaction, not used anymore ( #22 )  
- [x] CartItem table has no quantity field, so the remaining fields: id, cart_id, content_type, object_id ( #22 )
- [x] Cart has an additional is_completed field boolean ( #22 )

**Comment by 9gix** [comment]
https://github.com/exclusive-gix/cs2102-store/commit/09b76b7157241491ebc87feb63a63fda8cd23fe1 https://github.com/exclusive-gix/cs2102-store/commit/7d62e5700b12651280c3c6ae2c2a947889071e2f
