### ISSUE TITLE
List of small bugs and enhancements

### ISSUE THREAD

**Issue by digawp** [exclusive-gix/cs2102-store#51]
- [x] Title of music detail is `book.name`
- [x] `no_preview_available` path is wrong
- [x] Newlines are not preserved at the description on detail page
- [x] Put dropbox download link of images file to README
- [x] Duration in music view should be in minutes and seconds, instead of just seconds (#58)
- [x] Download link in readme is in a code block (so it is not shown) (#58)
- [x] Crew is not shown for book (#58)
- [x] No preview image for music detail page should be 250x250 instead of 150x150 (#58)
- [x] White bar if user is not logged in and there is no review (straight to master)
- [x] Duration in movie view should be in minutes (#61)
- [ ] `{% block preview %}` at base_detail.html should be changed to an image field since it only contains image, for consistency with base_list.html
- [ ] Price $0.00 should be 'Free'
- [ ] Refactor crew view in music
- [ ] Should go back to referer after logging in
- [ ] Footer glitch
- [ ] Plural for link (apps and movies)
- [ ] Input validation in Review form
- [ ] Links to nowhere (About and Contact)

More to come...

**Comment by digawp** [comment]
Just to notify the rest I'll work on the issue 4 of this thread (newline preservation)

**Comment by jkt001** [comment]
I am working on number 3 as well...  just to notify

**Comment by jkt001** [comment]
No.3 see PR #55
